cloudixio/AUTOPILOT_APP/urls.py
from django.urls import path, re_path

from . import views

app_name='autopilot_app'
urlpatterns=[
    # path('',views.hello,name='index'),
    # path('<int:pk>', views.DetailView.as_view(), name='consultant'),
    # path('<int:pk>/results', views.ResultsView.as_view(), name='mission'),
    
    #Lists URLS
    re_path(r'^consultants/$', views.ListConsultantView.as_view(), name='consultants'),
    path('missions/', views.ListMissionView.as_view(), name='missions'),
    path('timesheets/', views.ListTimesheetView.as_view(), name='timesheets'),
    path('missionsType/', views.ListMissionTypeView.as_view(), name='missionsType'),
    path('activitesType/', views.ListActivitesTypeView.as_view(), name='missionsType'),
    path('activitesMissions/', views.ListActivitesMissionsView.as_view(), name='activitesMissions'),
    
    #Detail URLS
    path('<int:pk>/consultantTimesheets', views.DetailConsltantTimesheets.as_view(), name='consultantTimesheets'),
    path('<int:pk>/consultant', views.DetailConsultantView.as_view(), name='consultant_detail'),
    path('<int:pk>/mission', views.DetailMissionView.as_view(), name='mission_detail'),
    path('<int:pk>/timesheet', views.DetailTimesheetView.as_view(), name='timesheet_detail'),
    path('<int:pk>/missionType', views.DetailTypeMissionView.as_view(), name='missionType_detail'),
    path('<int:pk>/activiteType', views.DetailActiviteTypeView.as_view(), name='activiteType_detail'),

   
    #Account urls
    path('<int:pk>/profil/', views.ProfilView.as_view(), name='profil'),
    path('inscription/', views.inscription, name='inscription'),
    path('connexion/', views.connexion, name='connexion'),
    
    
    #Test filter
    path('list/', views.list_consultants)
]

cloudixio/cloudixio/urls.py
from django.contrib import admin
from django.urls import path, include
from AUTOPILOT_APP import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', views.hello),
    path('about-us/', views.about),
    path('', include('AUTOPILOT_APP.urls')),
    # path('missions/', views.mission),
    # path('timesheets/', views.timeSheet)
]

cloudixio/AUTOPILOT_APP/forms.py
from types import AsyncGeneratorType
from django import forms
from .models import ActivitesMissions, ActivitesType, Competences, Consultant, Mission, TimeSheet

class FormInscription(forms.ModelForm):
    nom= forms.CharField(label="Nom")
    prenom= forms.CharField(label="prenom")
    email = forms.EmailField(label="Email")
    password = forms.CharField(label="Mot de passe")
    class Meta:
        model= Consultant
        fields=['nom','prenom','email','password']

class FormConnexion(forms.ModelForm):
    email = forms.EmailField(label="Email",widget=forms.TextInput(attrs={'placeholder': 'Jhon@address.com'}))
    password = forms.CharField(label="Mot de passe",widget=forms.PasswordInput(attrs={'placeholder': 'Votre mot de passe ...'}))
    class Meta:
        model= Consultant
        fields=['email','password']
        
        
#----------------------------------------------------
# Les form de Filtres
#----------------------------------------------------
class FiltresConsultant(forms.ModelForm): 
    idConsultant = forms.ModelChoiceField(Consultant.objects.all().values_list('idConsultant', flat=True).distinct(), empty_label="Id Consulant", widget = forms.Select(attrs = {'onchange' : "filter(this.value);"}))
    # nom = forms.ModelChoiceField(Consultant.objects.all().values_list('nom', flat=True).distinct(), empty_label="Nom",widget = forms.Select(attrs = {'onchange' : "filter(this.value);"}))
    # prenom=forms.ModelChoiceField(Consultant.objects.all().values_list('prenom', flat=True).distinct(), empty_label="Prénom")
    # competence=forms.ModelChoiceField(Competences.objects.all().values_list('description', flat=True).distinct(), empty_label="Compétence",widget = forms.Select(attrs = {'onchange' : "filter(this.value);"}))
    def __init__(self, *args, **kwargs):
        super(FiltresConsultant, self).__init__(*args, **kwargs)
        for field_name in self.fields:
            field = self.fields.get(field_name)
            # field.widget.attrs['placeholder'] = field.label
            field.label = ''
    class Meta:
        model= Consultant
        fields=['idConsultant']
# FiltresConsultant().as_ul()




class FiltresTimeSheet(forms.Form): 
    idMission = forms.ModelChoiceField(Mission.objects.filter(idMission__in=(TimeSheet.objects.all().values_list('idMission',flat=True).distinct())).values_list('nomMission',flat=True), empty_label="Mission")
    idConsultant = forms.ModelChoiceField(Consultant.objects.filter(idConsultant__in=(TimeSheet.objects.all().values_list('idConsultant',flat=True).distinct())).values_list('nom',flat=True), empty_label="Consulant")
    annee=forms.ModelChoiceField(TimeSheet.objects.all().values_list('annee', flat=True).distinct(), empty_label="Annee")
    semaine=forms.ModelChoiceField(TimeSheet.objects.all().values_list('semaine', flat=True).distinct(), empty_label="Semaine")
    tempsPasse=forms.ModelChoiceField(TimeSheet.objects.all().values_list('tempsPasse', flat=True).distinct(), empty_label="Temps passé")
    def __init__(self, *args, **kwargs):
        super(FiltresTimeSheet, self).__init__(*args, **kwargs)
        for field_name in self.fields:
            field = self.fields.get(field_name)
            # field.widget.attrs['placeholder'] = field.label
            field.label = ''
FiltresTimeSheet().as_ul()

class FiltresActivitesMissions(forms.Form): 
    idActivitesType = forms.ModelChoiceField(ActivitesType.objects.filter(idActivitesType__in=(ActivitesMissions.objects.all().values_list('idActivitesType',flat=True).distinct())).values_list('description',flat=True), empty_label="Mission")
    idMission = forms.ModelChoiceField(Mission.objects.filter(idMission__in=(ActivitesMissions.objects.all().values_list('idMission',flat=True).distinct())).values_list('nomMission',flat=True), empty_label="Mission")
    idConsultant = forms.ModelChoiceField(Consultant.objects.filter(idConsultant__in=(ActivitesMissions.objects.all().values_list('idConsultant',flat=True).distinct())).values_list('nom',flat=True), empty_label="Consulant")
    tjm=forms.ModelChoiceField(ActivitesMissions.objects.all().values_list('tjm', flat=True).distinct(), empty_label="TJM")
    estimationCharge=forms.ModelChoiceField(ActivitesMissions.objects.all().values_list('estimationCharge', flat=True).distinct(), empty_label="Estimation Charge")
    def __init__(self, *args, **kwargs):
        super(FiltresActivitesMissions, self).__init__(*args, **kwargs)
        for field_name in self.fields:
            field = self.fields.get(field_name)
            # field.widget.attrs['placeholder'] = field.label
            field.label = ''
FiltresTimeSheet().as_ul()

cloudixio/AUTOPILOT_APP/views.py
# from asyncio import constants

# from urllib import request





from django.views import generic
from django.urls import reverse
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

from AUTOPILOT_APP.models import Consultant, Mission, TimeSheet, MissionsType, ActivitesType, ActivitesMissions
from .filters import ConsultantFilter

from .forms import FiltresActivitesMissions, FiltresConsultant, FiltresTimeSheet, FormInscription, FormConnexion


def hello(request):
    consultants = Consultant.objects.all()
    
    return HttpResponse(f"""<h1>Hello Cloudixio<h1>
                        <h2>my favorite consultants: </h2>
                        <ul>
                        <li>identifiant : {consultants[0].idConsultant} Mr:{consultants[0].prenom} </li>
                        <li>identifiant : {consultants[1].idConsultant} Mr:{consultants[1].prenom}</li>
                        </ul>""")


def about(request):
    return HttpResponse("""<h1>About-us</h1>
                        CLOUDIXIO AIDE LES ORGANISATIONS À CROITRE, INNOVER, DÉVELOPPER LEURS CAPACITÉS, 
                        ET CRÉER DE NOUVEAUX BUSINESS<h2></h2>""")


class DetailConsltantTimesheets(generic.DetailView):
    model=Consultant
    template_name='AUTOPILOT_APP/filter/consultant_timesheets.html'
         


class ListConsultantView(generic.ListView):
    
    model= Consultant
    template_name ='AUTOPILOT_APP/list/list_consultants.html'
    #context_object_name = 'consultants' 

    def get_context_data(self, **kwargs):
    
        context = super().get_context_data(**kwargs)
        context['titre'] = 'Liste des consultants'
        context['filtres']= ConsultantFilter(self.request.GET, queryset=self.get_queryset())

        
        return context
    
    
  
    # def get(self, request, *args, **kwargs):
    #     # self.form = FiltresConsultant(self.request.GET or None,)
    #     return super(ListConsultantView, self).get(request, *args, **kwargs)

    # def post(self, request, *args, **kwargs):
    #     if self.request.POST:
        
    #         form = FiltresConsultant(self.request.POST)
    #         self.form=form
    #         if form.is_valid():
                
    #             print(form.cleaned_data['idConsultant'])
    #     else :
    #         self.form=FiltresConsultant()
    #     return super(ListConsultantView, self).get(request, *args, **kwargs)
            
  
  
  
    # def get_queryset(self):
    #     consultants=Consultant.objects.all()
        
    #     if(self.request.method=="POST"):
            

    #         # nom = self.request.POST.get('nom')

    #         # self.form.fields['nom'].choices = [(nom, nom)]

    #         if(self.form.is_valid()):
    #             consultants= Consultant.objects.filter(idConsultant=self.form.cleaned_data['idConsultant'])
    #             print(consultants)
     
 
    #     return consultants
   

   
     

class ListMissionView(generic.ListView):
    template_name= 'AUTOPILOT_APP/list/list_missions.html'
    context_object_name= 'missions'
    
    def get_queryset(self):
        return Mission.objects.all()
        
    
    def get_context_data(self, **kwargs):
       
        context = super().get_context_data(**kwargs)
   
        context['titre'] = 'Liste des missions'
        return context

 


class ListTimesheetView(generic.ListView):
    template_name= 'AUTOPILOT_APP/list/list_timesheets.html'
    context_object_name= 'timesheets'
 
    def get_queryset(self):
        return TimeSheet.objects.all()
    
    def get_context_data(self, **kwargs):
      
        context = super().get_context_data(**kwargs)
 
        context['titre'] = 'Liste de Timesheets'
        context['form'] = FiltresTimeSheet()
        return context


class ListMissionTypeView(generic.ListView):
    template_name= 'AUTOPILOT_APP/list/list_missionsType.html'
    context_object_name= 'missionsType'
    
    def get_queryset(self):
        return MissionsType.objects.all()
    
    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        context['titre'] = 'Liste de types missions'
        return context


class ListActivitesTypeView(generic.ListView):
    template_name= 'AUTOPILOT_APP/list/list_activitesType.html'
    context_object_name= 'activitesType'
    
    def get_queryset(self):
        return ActivitesType.objects.all()
        
    
    def get_context_data(self, **kwargs):
    
        context = super().get_context_data(**kwargs)

        context['titre'] = 'Liste des types d\'activites'
        return context
    
class ListActivitesMissionsView(generic.ListView):
    template_name= 'AUTOPILOT_APP/list/list_activitesMissions.html'
    context_object_name= 'activitesMissions'
    
    def get_queryset(self):
        return ActivitesMissions.objects.all()
        
    
    def get_context_data(self, **kwargs):
      
        context = super().get_context_data(**kwargs)
       
        context['titre'] = 'Liste des activites missions'
        context['consultants']= FiltresActivitesMissions()
        return context




class DetailConsultantView(generic.DetailView):
    model= Consultant
    template_name= 'AUTOPILOT_APP/detail/consultant_detail.html'
    
    
class DetailMissionView(generic.DetailView):
    model= Mission
    template_name='AUTOPILOT_APP/detail/mission_detail.html'
    
    
class DetailTimesheetView(generic.DetailView):
    model=TimeSheet
    template_name='AUTOPILOT_APP/detail/timesheet_detail.html'


class DetailTypeMissionView(generic.DetailView):
    model = MissionsType
    template_name='AUTOPILOT_APP/detail/missionType_detail.html'
    
    def get_context_data(self, **kwargs):
    
        context = super().get_context_data(**kwargs)
      
        context['titre'] = 'Détail type mission'
        return context
  
class DetailActiviteTypeView(generic.DetailView):
    model = ActivitesType
    template_name='AUTOPILOT_APP/detail/activiteType_detail.html'
    
    def get_context_data(self, **kwargs):
        
        context = super().get_context_data(**kwargs)
    
        context['titre'] = 'Détail type activité'
        return context



def inscription(request):
    if request.method == "POST":
        form = FormInscription(request.POST)
        context = {
            'form': form,
            'message': 'Inscription',
            'error':'',
            'register':''
        }

        if form.is_valid():
            if(Consultant.objects.filter(email=form.cleaned_data['email'])):
                context.update({'error':'Ce nom d\'utilisateur existe!'})
            else:
                if(form.save()):
                    context.update({'register':'OK'})
                    return HttpResponseRedirect('/connexion/')
                else:
                    context.update({'error':'inscription échouée veuillez réessayer !','register':'KO'})
    else:

        form = FormInscription()
        context = {
            'form': form,
            'message': 'Inscription',
            'error':''
        }
    return render(request, 'AUTOPILOT_APP/account/inscription.html', {"context": context})


def connexion(request):

    if request.method == "POST":
        form = FormConnexion(request.POST)
        context = {
            'form': form,
            'message': 'Connexion',
            'error': ''
        }
        if form.is_valid():
            if(Consultant.objects.filter(email=form.cleaned_data['email'])):
                consultant = Consultant.objects.get(email=form.cleaned_data['email'])

                if(consultant.password == form.cleaned_data['password']):
                    url = "/"+str(consultant.idConsultant) + "/profil/"
                    return HttpResponseRedirect(url)
                else:
                    context.update({'error': "mot de passe incorrecte"})

            else:
                context.update({'error': "Cette adresse email n'existe pas!"})

    else:

        form = FormConnexion()
        context = {
            'form': form,
            'message': 'Connexion',
            'error': ''
        }

    return render(request, 'AUTOPILOT_APP/account/connexion.html', {"context": context})


class ProfilView(generic.DetailView):
    model=Consultant
    template_name="AUTOPILOT_APP/account/profil.html"
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['titre'] = 'Profil du consultant'
        return context
    


#Test filter 

def list_consultants(request):
    f = ConsultantFilter(queryset=Consultant.objects.all())
    return render(request, 'AUTOPILOT_APP/test.html', {'filter': f})
   

cloudixio/AUTOPILOT_APP/templates/AUTOPILOT_APP/list/list_activitesMissions.html
{%extends 'AUTOPILOT_APP/base.html'%}

<!-- {% load bootstrap5 %} -->

{% block bootstrap5_content %}
{% load crispy_forms_tags %}

<div class="container">
    <div class="row">
        <div class="col-lg-4">
            <h3>Filtres</h3>
            {{consultants|crispy}}
        </div>

        <div class="col-lg-8">
            <h1>{% block title %}{{titre}}{% endblock %}</h1>
            <table id="list_missions" class="table table-info table-hover table-striped">
                <thead>
                    <tr>

                        <th scope="col">ID Activite Mission</th>
                        <th scope="col">Activite Type</th>
                        <th scope="col">Mission</th>
                        <th scope="col">Consultant</th>
                        <th scope="col">TJM</th>
                        <th scope="col">Estimation charge</th>

                    </tr>
                </thead>
                <tbody>
                    {%for actMission in activitesMissions %}
                    <tr>
                        <th scope="row">{{actMission.idActivitesMissions}}</th>
                        <td>{{actMission.idActivitesType}}</td>
                        <td>{{actMission.idMission}}</td>
                        <td>{{actMission.idConsultant}}</td>
                        <td>{{actMission.tjm}}</td>
                        <td>{{actMission.estimationCharge}}</td>

                    </tr>
                    {%endfor%}

                </tbody>
            </table>
        </div>
    </div>
</div>





{% autoescape off %}{% bootstrap_messages %}{% endautoescape %}



{% endblock %}

cloudixio/AUTOPILOT_APP/templates/AUTOPILOT_APP/list/list_activitesType.html
{%extends 'AUTOPILOT_APP/base.html'%}

<!-- {% load bootstrap5 %} -->

{% block bootstrap5_content %}
<div class="container">
    <h1>{% block title %}{{titre}}{% endblock %}</h1>
    <table id="list_missions" class="table table-info table-hover table-striped">
        <thead>
            <tr>
           
                <th scope="col">ID Activite Type</th>
                <th scope="col">Description</th>
              
            </tr>
        </thead>
        <tbody>
            {%for acType in activitesType %}
            <tr class="clickable" data-url="{% url 'autopilot_app:activiteType_detail' acType.idActivitesType %}"> 
                <th scope="row">{{acType.idActivitesType}}</th>
                <td>{{acType.description}}</td>

            </tr>
            {%endfor%}

        </tbody>
    </table>
</div>




{% autoescape off %}{% bootstrap_messages %}{% endautoescape %}



{% endblock %}

cloudixio/AUTOPILOT_APP/templates/AUTOPILOT_APP/list/list_consultants.html
{%extends 'AUTOPILOT_APP/base.html'%}

{% load bootstrap5 %}

{% block bootstrap5_content %}
{% load crispy_forms_tags %}
<div class="container">
    <div class="row">
        <div class="col-lg-4">
            <h3>Filtres</h3>
            

            <form  method="GET">
                <!-- {% csrf_token %} -->
                {% load crispy_forms_tags %} 
                {{filtres.form|crispy}}
               
                <button type="submit" class="btn btn-success d-flex justify-content-center">filtrer</button>
            </form>

        </div>

        <div class="col-lg-8">
            <h1>{% block title %}Consultants{% endblock %}</h1>
            <table id="list_consultants" class="table table-primary table-hover table-striped">
                <thead>
                    <tr>
                        <th scope="col">ID Consultant</th>
                        <th scope="col">nom</th>
                        <th scope="col">prenom</th>
                        <th scope="col">compétences</th>
                    </tr>
                </thead>
                <tbody>
                    {%for consultant in filtres.qs %}
                    <tr class="clickable"
                        data-url="{% url 'autopilot_app:consultantTimesheets' consultant.idConsultant %}">
                        <th scope="row">{{consultant.idConsultant}}</th>
                        <td class="nom">{{consultant.nom}}</td>
                        <td>{{consultant.prenom}}</td>
                        <td>
                            {%for comp in consultant.competences.all%}

                            {%if comp%}
                            {{comp}}

                            {%endif%}

                            {%endfor%}

                        </td>
                    </tr>
                    {%endfor%}

                </tbody>
            </table>
        </div>
    </div>
</div>




{% autoescape off %}{% bootstrap_messages %}{% endautoescape %}


{% endblock %}

cloudixio/AUTOPILOT_APP/templates/AUTOPILOT_APP/list/list_missions.html
{%extends 'AUTOPILOT_APP/base.html'%}

<!-- {% load bootstrap5 %} -->

{% block bootstrap5_content %}
<div class="container">
    <h1>{% block title %}{{titre}}{% endblock %}</h1>
    <table id="list_missions" class="table table-info table-hover table-striped">
        <thead>
            <tr>
           
                <th scope="col">ID Mission</th>
                <th scope="col">Nom Mission</th>
                <th scope="col">Date d'ouverture</th>
                <th scope="col">Date de clôture</th>
            </tr>
        </thead>
        <tbody>
            {%for mission in missions %}
            <tr class="clickable" data-url="{% url 'autopilot_app:mission_detail' mission.idMission %}"> 
                <th scope="row">{{mission.idMission}}</th>
                <th scope="row">{{mission.nomMission}}</th>
                <td>{{mission.startDate}}</td>
                <td>{{mission.endDate}}</td>

            </tr>
            {%endfor%}

        </tbody>
    </table>
</div>




{% autoescape off %}{% bootstrap_messages %}{% endautoescape %}



{% endblock %}

cloudixio/AUTOPILOT_APP/templates/AUTOPILOT_APP/list/list_missionsType.html
{%extends 'AUTOPILOT_APP/base.html'%}

<!-- {% load bootstrap5 %} -->

{% block bootstrap5_content %}
<div class="container">
    <h1>{% block title %} {{titre}}{% endblock %}</h1>
    <table id="list_missions" class="table table-info table-hover table-striped">
        <thead>
            <tr>
           
                <th scope="col">ID MissionType</th>

                <th scope="col">Titre</th>
                <th scope="col">Description</th>
            </tr>
        </thead>
        <tbody>
            {%for missionType in missionsType%}
            <tr class="clickable" data-url="{% url 'autopilot_app:missionType_detail' missionType.idMissionType %}"> 
                <th scope="col">{{missionType.idMissionType}}</th>
           
                <td>{{missionType.titre}}</td>
                <td>{{missionType.description}}</td>

            </tr>
            {%endfor%}

        </tbody>
    </table>
</div>




{% autoescape off %}{% bootstrap_messages %}{% endautoescape %}


</div>

{% endblock %}

cloudixio/AUTOPILOT_APP/templates/AUTOPILOT_APP/list/list_timesheets.html
{%extends 'AUTOPILOT_APP/base.html'%}

{% load bootstrap5 %}

{% block bootstrap5_content %}
{% load crispy_forms_tags %}
<div class="text-center h2">{% block title %}{{titre}}{% endblock %}</div>
<div class="container ">
    
    <div class="row ">
        
        <div class="col justify-content-center">
            {% csrf_token %}
            {{form.idConsultant|as_crispy_field}}
        </div>
        <div class="col justify-content-center">
            {% csrf_token %}
            {{form.idMission|as_crispy_field}}
        </div>
        <div class="col justify-content-center">
            {% csrf_token %}
            {{form.annee|as_crispy_field}}
        </div>
        <div class="col justify-content-center">
            {% csrf_token %}
            {{form.semaine|as_crispy_field}}
        </div>
        <div class="col justify-content-center">
            {% csrf_token %}
            {{form.tempsPasse|as_crispy_field}}
        </div>
    </div>
    <div class="row">
        <table id="list_timesheets" class="table table-success table-hover table-striped">
            <thead>
                <tr>
                    <th scope="col">ID Timesheet</th>
                    <th scope="col">Consultant</th>
                    <th scope="col">Mission</th>
                    <th scope="col">Annee</th>
                    <th scope="col">Semaine</th>
                    <th scope="col">Temps passé</th>
                </tr>
            </thead>
            <tbody>
                {%for timesheet in timesheets %}
                <tr class="clickable"
                    data-url="{% url 'autopilot_app:consultantTimesheets' timesheet.idConsultant.idConsultant %}">
                    <th scope="row">{{timesheet.idTimeSheet}}</th>
                    <td>{{timesheet.idConsultant}}</td>
                    <td>{{timesheet.idMission}}</td>
                    <td>{{timesheet.annee}}</td>
                    <td>{{timesheet.semaine}}</td>
                    <td>{{timesheet.tempsPasse}}</td>

                </tr>
                {%endfor%}

            </tbody>
        </table>
    </div>
</div>




{% autoescape off %}{% bootstrap_messages %}{% endautoescape %}


{% endblock %}