cloudixio/AUTOPILOT_APP/urls.py
from django.urls import path, re_path

from . import views

app_name='autopilot_app'
urlpatterns=[
    # path('',views.hello,name='index'),
    # path('<int:pk>', views.DetailView.as_view(), name='consultant'),
    # path('<int:pk>/results', views.ResultsView.as_view(), name='mission'),
    
    #Lists URLS
    re_path(r'^consultants/$', views.ListConsultantView.as_view(), name='consultants'),
    path('missions/', views.ListMissionView.as_view(), name='missions'),
    path('timesheets/', views.ListTimesheetView.as_view(), name='timesheets'),
    path('missionsType/', views.ListMissionTypeView.as_view(), name='missionsType'),
    path('activitesType/', views.ListActivitesTypeView.as_view(), name='missionsType'),
    path('activitesMissions/', views.ListActivitesMissionsView.as_view(), name='activitesMissions'),
    
    #Detail URLS
    path('<int:pk>/consultantTimesheets', views.DetailConsltantTimesheets.as_view(), name='consultantTimesheets'),
    path('<int:pk>/consultant', views.DetailConsultantView.as_view(), name='consultant_detail'),
    path('<int:pk>/mission', views.DetailMissionView.as_view(), name='mission_detail'),
    path('<int:pk>/timesheet', views.DetailTimesheetView.as_view(), name='timesheet_detail'),
    path('<int:pk>/missionType', views.DetailTypeMissionView.as_view(), name='missionType_detail'),
    path('<int:pk>/activiteType', views.DetailActiviteTypeView.as_view(), name='activiteType_detail'),

   
    #Account urls
    path('<int:pk>/profil/', views.ProfilView.as_view(), name='profil'),
    path('inscription/', views.inscription, name='inscription'),
    path('connexion/', views.connexion, name='connexion'),
    
    
    #Test filter
    path('list/', views.list_consultants)
]

cloudixio/cloudixio/urls.py
from django.contrib import admin
from django.urls import path, include
from AUTOPILOT_APP import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', views.hello),
    path('about-us/', views.about),
    path('', include('AUTOPILOT_APP.urls')),
    # path('missions/', views.mission),
    # path('timesheets/', views.timeSheet)
]

cloudixio/AUTOPILOT_APP/models.py
# from msilib.schema import Class


from django.db import models
import datetime

class Competences(models.Model):
    idCompetence = models.AutoField(db_column='idCompetence', primary_key=True)  # Field name made lowercase.
    description = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'competences'

    def __str__(self):
        return self.description
    
class Consultant(models.Model):
    idConsultant = models.fields.BigAutoField(primary_key=True,null=False)
    nom = models.fields.CharField(max_length=100, default='NULL')
    prenom = models.fields.CharField(max_length=100, default='NULL')
    # email= models.fields.EmailField(default='')
    # password= models.fields.CharField(max_length=100)
    competences= models.ManyToManyField(Competences, through="ConsultantsCompetences")
    class Meta:
        managed = False
        db_table = 'consultant'
    def __str__(self):
        return str(self.prenom+" "+self.nom)



    
class ConsultantsCompetences(models.Model):
    idConsultantsCompetences = models.AutoField(blank=True, primary_key=True)
    idCompetence = models.ForeignKey(Competences, models.DO_NOTHING, db_column='idCompetence')  # Field name made lowercase.
    idConsultant = models.ForeignKey(Consultant, models.DO_NOTHING, db_column='idConsultant')  # Field name made lowercase.
    

    class Meta:
        managed = False
        db_table = 'consultantsCompetences'



class MissionsType(models.Model):
    idMissionType = models.fields.BigAutoField(primary_key=True, null=False, db_column='idMissionType')
    titre= models.fields.TextField(blank=True, null=True, max_length=50)
    description=models.fields.TextField(blank=True, null=True, max_length=50)
    
    class Meta:
        managed = False
        db_table = 'missionsType'
    
    def __str__(self):
        return str(self.titre)


class Mission(models.Model):
    idMission= models.fields.BigAutoField(primary_key=True, null=False)
    idMissionType= models.ForeignKey(MissionsType, null=True,on_delete=models.SET_NULL,db_column='idMissionType')
    startDate= models.fields.DateField(null=False)
    endDate = models.fields.DateField()
    nomMission= models.fields.TextField(null=False)
    
    class Meta:
        managed = False
        db_table = 'missions'
        
    def __str__(self):
        return str(self.nomMission)




class TimeSheet(models.Model):
    idTimeSheet = models.fields.BigAutoField(primary_key=True, null=False)
    idMission = models.ForeignKey(Mission, null=True, on_delete=models.SET_NULL, db_column='idMission')
    idConsultant = models.ForeignKey(Consultant, null=True, on_delete=models.SET_NULL, db_column='idConsultant')
    annee = models.fields.SmallIntegerField(choices=[(r,r) for r in range(2000, datetime.date.today().year+30)])
    semaine = models.fields.SmallIntegerField(choices=[(r,r) for r in range(1,53)])
    tempsPasse = models.FloatField(db_column='tempsPassé', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'timeSheet'

    def __str__(self):
        strIdTimesheet = str(self.idTimeSheet)
        return strIdTimesheet 


class ActivitesType(models.Model):
    idActivitesType = models.AutoField(db_column='idActivitesType', primary_key=True)  # Field name made lowercase.
    description = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'activitesType'

    def __str__(self):
        return self.description
    

class ActivitesMissions(models.Model):
    idActivitesMissions = models.AutoField(db_column='idActivitesMissions', primary_key=True)  # Field name made lowercase.
    idActivitesType = models.ForeignKey('Activitestype',models.DO_NOTHING,db_column='idActivitesType')  # Field name made lowercase.
    idMission = models.ForeignKey('Mission', models.DO_NOTHING, db_column='idMission')  # Field name made lowercase.
    idConsultant = models.ForeignKey('Consultant', models.DO_NOTHING, db_column='idConsultant')  # Field name made lowercase.
    tjm = models.FloatField(blank=True, null=True)
    estimationCharge = models.FloatField(db_column='estimationCharge', blank=True, null=True)  # Field name made lowercase.
    # devise = models.TextField(blank=True, null=True)
    # tauxchangeeur = models.FloatField(db_column='tauxChangeEur', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'activitesMissions'
        # ordering = ['idConsultant']

cloudixio/AUTOPILOT_APP/views.py
# from asyncio import constants

# from urllib import request





from django.views import generic
from django.urls import reverse
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

from AUTOPILOT_APP.models import Consultant, Mission, TimeSheet, MissionsType, ActivitesType, ActivitesMissions
from .filters import ConsultantFilter

from .forms import FiltresActivitesMissions, FiltresConsultant, FiltresTimeSheet, FormInscription, FormConnexion


def hello(request):
    consultants = Consultant.objects.all()
    
    return HttpResponse(f"""<h1>Hello Cloudixio<h1>
                        <h2>my favorite consultants: </h2>
                        <ul>
                        <li>identifiant : {consultants[0].idConsultant} Mr:{consultants[0].prenom} </li>
                        <li>identifiant : {consultants[1].idConsultant} Mr:{consultants[1].prenom}</li>
                        </ul>""")


def about(request):
    return HttpResponse("""<h1>About-us</h1>
                        CLOUDIXIO AIDE LES ORGANISATIONS À CROITRE, INNOVER, DÉVELOPPER LEURS CAPACITÉS, 
                        ET CRÉER DE NOUVEAUX BUSINESS<h2></h2>""")


class DetailConsltantTimesheets(generic.DetailView):
    model=Consultant
    template_name='AUTOPILOT_APP/filter/consultant_timesheets.html'
         


class ListConsultantView(generic.ListView):
    
    model= Consultant
    template_name ='AUTOPILOT_APP/list/list_consultants.html'
    #context_object_name = 'consultants' 

    def get_context_data(self, **kwargs):
    
        context = super().get_context_data(**kwargs)
        context['titre'] = 'Liste des consultants'
        context['filtres']= ConsultantFilter(self.request.GET, queryset=self.get_queryset())

        
        return context
    
    
  
    # def get(self, request, *args, **kwargs):
    #     # self.form = FiltresConsultant(self.request.GET or None,)
    #     return super(ListConsultantView, self).get(request, *args, **kwargs)

    # def post(self, request, *args, **kwargs):
    #     if self.request.POST:
        
    #         form = FiltresConsultant(self.request.POST)
    #         self.form=form
    #         if form.is_valid():
                
    #             print(form.cleaned_data['idConsultant'])
    #     else :
    #         self.form=FiltresConsultant()
    #     return super(ListConsultantView, self).get(request, *args, **kwargs)
            
  
  
  
    # def get_queryset(self):
    #     consultants=Consultant.objects.all()
        
    #     if(self.request.method=="POST"):
            

    #         # nom = self.request.POST.get('nom')

    #         # self.form.fields['nom'].choices = [(nom, nom)]

    #         if(self.form.is_valid()):
    #             consultants= Consultant.objects.filter(idConsultant=self.form.cleaned_data['idConsultant'])
    #             print(consultants)
     
 
    #     return consultants
   

   
     

class ListMissionView(generic.ListView):
    template_name= 'AUTOPILOT_APP/list/list_missions.html'
    context_object_name= 'missions'
    
    def get_queryset(self):
        return Mission.objects.all()
        
    
    def get_context_data(self, **kwargs):
       
        context = super().get_context_data(**kwargs)
   
        context['titre'] = 'Liste des missions'
        return context

 


class ListTimesheetView(generic.ListView):
    template_name= 'AUTOPILOT_APP/list/list_timesheets.html'
    context_object_name= 'timesheets'
 
    def get_queryset(self):
        return TimeSheet.objects.all()
    
    def get_context_data(self, **kwargs):
      
        context = super().get_context_data(**kwargs)
 
        context['titre'] = 'Liste de Timesheets'
        context['form'] = FiltresTimeSheet()
        return context


class ListMissionTypeView(generic.ListView):
    template_name= 'AUTOPILOT_APP/list/list_missionsType.html'
    context_object_name= 'missionsType'
    
    def get_queryset(self):
        return MissionsType.objects.all()
    
    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        context['titre'] = 'Liste de types missions'
        return context


class ListActivitesTypeView(generic.ListView):
    template_name= 'AUTOPILOT_APP/list/list_activitesType.html'
    context_object_name= 'activitesType'
    
    def get_queryset(self):
        return ActivitesType.objects.all()
        
    
    def get_context_data(self, **kwargs):
    
        context = super().get_context_data(**kwargs)

        context['titre'] = 'Liste des types d\'activites'
        return context
    
class ListActivitesMissionsView(generic.ListView):
    template_name= 'AUTOPILOT_APP/list/list_activitesMissions.html'
    context_object_name= 'activitesMissions'
    
    def get_queryset(self):
        return ActivitesMissions.objects.all()
        
    
    def get_context_data(self, **kwargs):
      
        context = super().get_context_data(**kwargs)
       
        context['titre'] = 'Liste des activites missions'
        context['consultants']= FiltresActivitesMissions()
        return context




class DetailConsultantView(generic.DetailView):
    model= Consultant
    template_name= 'AUTOPILOT_APP/detail/consultant_detail.html'
    
    
class DetailMissionView(generic.DetailView):
    model= Mission
    template_name='AUTOPILOT_APP/detail/mission_detail.html'
    
    
class DetailTimesheetView(generic.DetailView):
    model=TimeSheet
    template_name='AUTOPILOT_APP/detail/timesheet_detail.html'


class DetailTypeMissionView(generic.DetailView):
    model = MissionsType
    template_name='AUTOPILOT_APP/detail/missionType_detail.html'
    
    def get_context_data(self, **kwargs):
    
        context = super().get_context_data(**kwargs)
      
        context['titre'] = 'Détail type mission'
        return context
  
class DetailActiviteTypeView(generic.DetailView):
    model = ActivitesType
    template_name='AUTOPILOT_APP/detail/activiteType_detail.html'
    
    def get_context_data(self, **kwargs):
        
        context = super().get_context_data(**kwargs)
    
        context['titre'] = 'Détail type activité'
        return context



def inscription(request):
    if request.method == "POST":
        form = FormInscription(request.POST)
        context = {
            'form': form,
            'message': 'Inscription',
            'error':'',
            'register':''
        }

        if form.is_valid():
            if(Consultant.objects.filter(email=form.cleaned_data['email'])):
                context.update({'error':'Ce nom d\'utilisateur existe!'})
            else:
                if(form.save()):
                    context.update({'register':'OK'})
                    return HttpResponseRedirect('/connexion/')
                else:
                    context.update({'error':'inscription échouée veuillez réessayer !','register':'KO'})
    else:

        form = FormInscription()
        context = {
            'form': form,
            'message': 'Inscription',
            'error':''
        }
    return render(request, 'AUTOPILOT_APP/account/inscription.html', {"context": context})


def connexion(request):

    if request.method == "POST":
        form = FormConnexion(request.POST)
        context = {
            'form': form,
            'message': 'Connexion',
            'error': ''
        }
        if form.is_valid():
            if(Consultant.objects.filter(email=form.cleaned_data['email'])):
                consultant = Consultant.objects.get(email=form.cleaned_data['email'])

                if(consultant.password == form.cleaned_data['password']):
                    url = "/"+str(consultant.idConsultant) + "/profil/"
                    return HttpResponseRedirect(url)
                else:
                    context.update({'error': "mot de passe incorrecte"})

            else:
                context.update({'error': "Cette adresse email n'existe pas!"})

    else:

        form = FormConnexion()
        context = {
            'form': form,
            'message': 'Connexion',
            'error': ''
        }

    return render(request, 'AUTOPILOT_APP/account/connexion.html', {"context": context})


class ProfilView(generic.DetailView):
    model=Consultant
    template_name="AUTOPILOT_APP/account/profil.html"
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['titre'] = 'Profil du consultant'
        return context
    


#Test filter 

def list_consultants(request):
    f = ConsultantFilter(queryset=Consultant.objects.all())
    return render(request, 'AUTOPILOT_APP/test.html', {'filter': f})
   

cloudixio/AUTOPILOT_APP/templates/AUTOPILOT_APP/account/connexion.html
{%extends 'AUTOPILOT_APP/base.html'%}

{% load bootstrap5 %}
{% load static %}

{% block bootstrap5_content %}



<div class="my-5 py-2 container bg-primary border rounded-10" style="--bs-bg-opacity:.8;">

    <div class="row justify-content-center ">
        <div class="d-flex py-5 px-5 align-content-center col-sm-10 col-md-6 text-light justify-content-center">
            <img src= "{% static 'AUTOPILOT_APP/logo_cloudixIO.png' %}" class="rounded mx-auto d-block" alt="...">
        </div>
        <div class="col-sm-10 col-md-6 text-light">
            <div class="d-flex fs-1 text-light justify-content-center">{{context.message|upper}}</div>
            <h3 class="text-success">{{context.register}}</h3>
            <h3 class="text-danger">{{context.error}}</h3>
            <form action="/connexion/" method="post">
                {% csrf_token %}
                {% load crispy_forms_tags %}
                {{context.form|crispy}}

                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label" for="exampleCheck1">Check me out</label>
                </div>
                <button type="submit" class="btn btn-success">Se connecter</button>
            </form>
        </div>
     
    </div>
</div>
{% autoescape off %}{% bootstrap_messages %}{% endautoescape %}



{% endblock %}

cloudixio/AUTOPILOT_APP/templates/AUTOPILOT_APP/account/inscription.html
{%extends 'AUTOPILOT_APP/base.html'%}

{% load static %}
{% load bootstrap5 %}


{% block bootstrap5_content %}

<div class="container justify-content-center bg-primary bg-gradient" style="--bs-bg-opacity: .9;">
    <div class="row my-5 py-3  justify-content-center">
        <div class="d-flex fs-1 text-light justify-content-center">{%block title%}{{context.message|upper}}{%endblock%}</div>
        <div class="d-flex py-2 my-5 align-content-center col-sm-10 col-md-6 text-light justify-content-center">
            <img src= "{% static 'AUTOPILOT_APP/logo_cloudixIO.png' %}" class="rounded mx-auto d-block" alt="...">
        </div>
        <div class="col-sm-10 col-md-6 text-light">
            
            <h3 class="text-danger">{{context.error}}</h3>
            <form action="/inscription/" method="post">
                {% csrf_token %}
                {% load crispy_forms_tags %} 
                {{context.form|crispy}}

                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label" for="exampleCheck1">Check me out</label>
                </div>
                <button type="submit" class="btn btn-success d-flex justify-content-center">s'inscrire</button>
            </form>
        </div>
    </div>
</div>
{% autoescape off %}{% bootstrap_messages %}{% endautoescape %}



{% endblock %}

cloudixio/AUTOPILOT_APP/templates/AUTOPILOT_APP/account/profil.html
{%extends 'AUTOPILOT_APP/base.html'%}

<!-- {% load bootstrap5 %} -->

{% block bootstrap5_content %}
<div class="container">
    <h1>{% block title %}{{titre}}{% endblock %}</h1>
    <table id="consultant" class="table table-primary table-hover table-striped">
        <thead>
            <tr>
                <th scope="col">nom</th>
                <th scope="col">prenom</th>
                <th scope="col">Email</th>
            </tr>
        </thead>
        <tbody>

            <tr>

                <td>{{consultant.nom}}</td>
                <td>{{consultant.prenom}}</td>
                <td>{{consultant.email}}</td>

            </tr>


        </tbody>
    </table>
</div>






<div class="container">
    <h1>Timesheets du consultant</h1>


    <div class="container">

        <div class="row">

            <table class="table table-success table-hover" id="consultant_timesheets">
                <thead>
                    <tr>
                        <th scope="col">ID Mission</th>
                        <th scope="col">Annee</th>
                        <th scope="col">Semaine</th>
                    </tr>
                </thead>
                <tbody>
                    {%for ts in consultant.timesheet_set.all %}

                    <tr class="clickable" data-url="{% url 'autopilot_app:mission_detail' ts.idMission_id %}">
                        <th scope="row">{{ts.idMission_id}}</th>
                        <td>{{ts.annee}}</td>
                        <td>{{ts.semaine}}</td>

                    </tr>
                    {%endfor%}
                </tbody>
            </table>
        </div>

    </div>
</div>


{% autoescape off %}{% bootstrap_messages %}{% endautoescape %}




{% endblock %}